config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'

  resources :certificates do
    resources :subscribers
    resources :import_subscribers, only: %i[new create]
    resource :send_by_email, only: %i[create]
  end

  resources :templates
  resources :issues, only: %i[index update destroy]
  resources :validates, only: %i[new create show]
  resources :usernames, only: %i[edit update]

  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    authenticate :user, lambda { |user| user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/views/templates/_form.html.erb
<%= simple_form_for(@template) do |f| %>
  <%= f.input :name, autofocus: true %>
  <%= f.input :font_color, input_html: { type: 'color' } %>

  <div class="card">
    <div class="card-header bg-success text-white"><%= t('hint.title.template') %></div>
    <div class="card-body">
      <%= show_image(@template, @template.name) %>
      <%= f.input :image_cache, as: :hidden %>
      <%= f.input :image, as: :file, hint: t('hint.image', size: '845x597'), input_html: { class: 'form-control' } %>

      <% if @template.name? %>
        <%= f.check_box :remove_image %>
        <%= label_tag "template_remove_image", "#{t('title.action.destroy')} #{t('mongoid.attributes.template.image')}" %>
      <% end %>
    </div>
  </div>

  <hr/>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to t('title.action.back'), templates_path, class: 'btn btn-secondary' %>
<% end %>

app/views/templates/_index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to "#{t('title.action.new')} #{t('mongoid.models.template')}", new_template_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-10 d-flex justify-content-end">
    <%= render 'shared/paginate', pagy: @pagy %>
  </div>
</div>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th width="40%"><%= t('mongoid.attributes.template.name') %></th>
      <th width="15%"><%= t('mongoid.attributes.template.font_color') %></th>
      <th width="10%" class="text-center"><%= t('mongoid.attributes.template.image') %></th>
      <th width="20%" class="text-center"><%= t('title.action.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><span class="badge" style="color: <%= template.font_color %>"><%= template.font_color %></span></td>
        <td class="text-center"><%= show_image(template, template.name) %></td>
        <td class="text-center">
          <%= link_to t('title.action.show'), template, class: 'btn btn-primary' %>
          <%= link_to t('title.action.edit'), edit_template_path(template), class: 'btn btn-primary' %>
          <%= link_to t('title.action.destroy'), template, class: 'btn btn-danger', method: :delete, data: { confirm: t('title.action.are_you_sure') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/templates/_show.html.erb
<table class="table table-responsive">
  <tbody>
    <tr>
      <th><%= t('mongoid.attributes.template.name') %></th>
      <td><%= @template.name %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.template.font_color') %></th>
      <td><span class="badge" style="color: <%= @template.font_color %>"><%= @template.font_color %></span></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.template.image') %></th>
      <td><%= show_image(@template, @template.name, '450x250') %></td>
    </tr>
  </tbody>
</table>

<%= link_to t('title.action.edit'), edit_template_path(@template), class: 'btn btn-primary' %>
<%= link_to t('title.action.back'), templates_path, class: 'btn btn-secondary' %>

app/views/templates/edit.html.erb
<%= render partial: 'form', layout: 'shared/form', locals: { cols: 6, title: "#{t('title.action.editing')} #{t('mongoid.models.template')}", template: @template } %>

app/views/templates/index.html.erb
<%= render partial: 'index', layout: 'shared/form', locals: { cols: 12,
  title: "#{@records.size} #{t('title.models.templates')}" } %>

app/views/templates/new.html.erb
<%= render partial: 'form', layout: 'shared/form', locals: { cols: 6, title: "#{t('title.action.new')} #{t('mongoid.models.template')}", template: @template } %>

app/views/templates/show.html.erb
<%= render partial: 'show', layout: 'shared/form', locals: { cols: 7, title: t('mongoid.models.template') } %>