config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'

  resources :certificates do
    resources :subscribers
    resources :import_subscribers, only: %i[new create]
    resource :send_by_email, only: %i[create]
  end

  resources :templates
  resources :issues, only: %i[index update destroy]
  resources :validates, only: %i[new create show]
  resources :usernames, only: %i[edit update]

  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    authenticate :user, lambda { |user| user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/subscriber.rb
class Subscriber
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :theme, type: String

  belongs_to :user
  belongs_to :profile
  belongs_to :certificate
  has_many   :downloads, dependent: :destroy

  accepts_nested_attributes_for :user

  validates_presence_of :certificate_id, :profile_id
  validates_uniqueness_of :user, scope: %i[profile certificate theme]
  validates_length_of :theme, maximum: 100

  scope :with_relations, -> do
    includes(:user, :profile, :certificate, :downloads)
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save do
    self.theme = nil unless profile.has_theme?
  end

  before_create do
    user_found = User.find_by(email: user.email)

    if user_found
      self.user = user_found
    else
      user.password = rand(111_111_11..999_999_99)
    end
  end

  def send_certificate_by_email
    CertificateMailer.with(subscriber_id: id.to_s).with_attachment.deliver_later
  end

  def generate_certificate
    CertificateGenerator.new(self)
  end

  def certificate_file_name
    user_name = user.full_name.parameterize
    certificate_title = certificate.title.parameterize
    profile_name = profile.name.parameterize

    "certifico_#{user_name}_#{certificate_title}_#{profile_name}.pdf"
  end

  def create_certificate(pdf_file)
    directory = Rails.root.join('tmp', 'certificates').to_path
    Dir.mkdir(directory) unless File.exist?(directory)

    generate_certificate.render(pdf_file)

    downloads.create
  end

  def self.search(params, certificate)
    filter = conditions(certificate, params[:profile], params[:search])

    records = Subscriber.with_relations.where(filter)
                        .sort_by { |subscriber| subscriber.user.full_name }

    { records: records, count: records.size }
  end

  def self.conditions(certificate, profile, search)
    conditions = { certificate: certificate }

    conditions[:profile] = Profile.find_by(name: profile) unless profile.blank?

    conditions['user_id'] = user_ids(search) unless search.blank?

    conditions
  end

  def self.user_ids(search)
    regex = Regexp.new(Regexp.escape(search), Regexp::IGNORECASE)

    user_ids = User.where(email: regex).pluck(:id)

    user_ids += User.where(full_name: regex).pluck(:id)

    { '$in' => user_ids }
  end

  def self.import(certificate, profile_id, sheet)
    profile = Profile.find(profile_id)

    import_subscriber(sheet, certificate, profile)
  end

  def self.raise_invalid_email(email)
    notice = I18n.t('notice.invalid_email', email: email)

    raise notice unless email.match?(VALID_EMAIL_REGEX)
  end

  def self.normalize_name(name)
    name.titleize
        .gsub(/D. /, &:downcase)
        .gsub(/D.. /, &:downcase)
        .gsub(/E /, &:downcase)
        .gsub(/^á/, &:upcase)
        .gsub(/^â/, &:upcase)
        .gsub(/^é/, &:upcase)
        .gsub(/^ó/, &:upcase)
        .gsub(/ á/, &:upcase)
        .gsub(/ â/, &:upcase)
        .gsub(/ é/, &:upcase)
        .gsub(/ ó/, &:upcase)
  end

  def self.import_subscriber(sheet, certificate, profile)
    sheet.each do |line|
      email = line[0].downcase
      name = normalize_name(line[1])

      raise_invalid_email(email)

      user = find_user(email: email, name: name, user_name: email.split('@').first.delete('.'))

      args = { user: user, certificate: certificate, profile: profile, theme: line[2] }

      Subscriber.find_or_create_by(select_fields(**args))
    end
  end

  def self.select_fields(**args)
    profile = args[:profile]
    theme = args[:theme]

    fields = { user: args[:user], certificate: args[:certificate],
               profile: profile }

    fields[:theme] = theme if profile.has_theme && !theme.blank?

    fields
  end

  def self.find_user(email:, name:, user_name:)
    user = User.find_by(email: email)

    user ||= User.create(email: email, full_name: name, user_name: user_name,
                         password: rand(11_111_111..99_999_999))

    user
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_certificate_and_profiles, only: %i[index new edit create update destroy]
  before_action :set_subscriber, only: %i[edit update destroy]
  before_action :authorization, only: %i[edit]

  def index
    session[:back_to] = certificate_subscribers_path(@certificate)

    query = Subscriber.search(params, @certificate)
    count = query[:count]
    @pagy, @records = pagy(query[:records], count: count)
    @subscribers_count = count
  end

  def new
    @subscriber = Subscriber.new

    @subscriber.user = User.new
  end

  def edit; end

  def create
    @subscriber = @certificate.subscribers.new(subscriber_params)

    if @subscriber.save
      redirect_to certificate_subscribers_path(@certificate),
                  notice: t('notice.created', model: t('mongoid.models.subscriber'))
    else
      render :new
    end
  end

  def update
    if @subscriber.update(subscriber_params)
      redirect_to certificate_subscribers_path(@certificate),
                  notice: t('notice.updated', model: t('mongoid.models.subscriber')) and return
    end

    message = @subscriber.errors.messages[:user_id][0]

    if message
      redirect_to edit_certificate_subscriber_path(@certificate, @subscriber),
                  alert: "#{t('mongoid.models.profile')} #{message}"
    else
      set_subscriber
      render :edit
    end
  end

  def destroy
    @subscriber.destroy

    return unless @subscriber.errors.blank?

    redirect_to certificate_subscribers_path(@certificate),
                notice: t('notice.destroyed', model: t('mongoid.models.subscriber'))
  end

  private

  def pagy_get_items(array, pagy)
    array[pagy.offset, pagy.items]
  end

  def subscriber_params
    params.require(:subscriber).permit(
      :profile_id, :theme,
      user_attributes: %i[email full_name user_name]
    )
  end

  def set_certificate_and_profiles
    @certificate = current_user.certificates.find(params[:certificate_id])

    @profiles = Profile.all.by_name
  end

  def set_subscriber
    @subscriber = @certificate.subscribers.find(params[:id])
  end

  def authorization
    return if @subscriber

    redirect_to certificate_path(@certificate),
                notice: t('notice.not_found', model: t('mongoid.models.subscriber')) and return
  end
end

app/views/subscribers/_form.html.erb
<%= simple_form_for @subscriber, url: url do |subscriber| %>
  <%= subscriber.simple_fields_for :user do |user| %>
    <% if form == 'new' %>
      <%= user.input :email, autofocus: true %>
      <%= user.input :user_name %>
      <%= user.input :full_name %>
    <% end %>

    <%= subscriber.input :profile_id, collection: @profiles, input_html: { class: 'form-select' } %>

    <% if form == 'new' || (form == 'edit' && @subscriber.profile.has_theme?) %>
      <%= subscriber.input :theme %>
    <% end %>

    <%= subscriber.button :submit, class: 'btn btn-primary' %>
    <%= link_to t('title.action.back'), certificate_subscribers_path(@certificate), class: 'btn btn-secondary' %>
  <% end %>
<% end %>

app/views/subscribers/_index.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_tag(certificate_subscribers_path(@certificate), method: :get, class: "form-inline", id: "search-form") do %>
      <div class="row g-3">
        <div class="col-auto">
          <%= select_tag 'profile', options_from_collection_for_select(@profiles, 'name', 'name', params[:profile]), include_blank: t('title.action.all'), class: 'form-select' %>
        </div>
        <div class="col-auto">
          <%= text_field_tag(:search, params[:search], placeholder: t('title.action.search_for_name_or_email'), class: 'form-control', size: '30') %>
        </div>
        <div class="col-auto">
          <%= submit_tag(t('title.action.search'), class: 'btn btn-primary') %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-4 d-flex justify-content-end">
    <% if @subscribers_count.positive? %>
      <%= form_tag(certificate_send_by_email_path(@certificate), method: :post, class: "form-inline") do %>
        <%= submit_tag("#{t('title.action.send')} #{t('title.models.certificates')}",
                       class: 'btn btn-primary',
                       data: { confirm: t('title.action.send_confirm', count: @subscribers_count) }) %>
        <%= hidden_field_tag 'profile', params[:profile] %>
      <% end %>
    <% end %>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-4">
    <%= link_to "#{t('title.action.new')} #{t('mongoid.models.subscriber')}",
                new_certificate_subscriber_path(@certificate), class: 'btn btn-primary' %>
    <%= link_to "#{t('title.action.import')} #{t('title.models.subscribers')}",
                new_certificate_import_subscriber_path(@certificate), class: 'btn btn-primary' %>
    <%= link_to t('title.action.back'), certificates_path, class: 'btn btn-secondary' %>
  </div>
  <div class="col-md-8 d-flex justify-content-end">
    <%= render 'shared/paginate', pagy: @pagy %>
  </div>
</div>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th><%= t('mongoid.attributes.user.full_name') %></th>
      <th><%= t('mongoid.attributes.user.email') %></th>
      <th><%= t('mongoid.attributes.subscriber.profile_id') %></th>
      <th><%= t('mongoid.attributes.subscriber.theme') %></th>
      <th class="text-center"><%= t('title.subscriber.downloads') %></th>
      <th colspan="5" class="text-center"><%= t('title.action.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |subscriber| %>
      <tr>
        <td><%= subscriber.user.full_name %></td>
        <td><%= subscriber.user.email %></td>
        <td><%= subscriber.profile.name %></td>
        <td><%= subscriber.theme %></td>
        <td class="text-center">
          <span class="badge rounded-pill bg-dark"><%= subscriber.downloads.size %></span>
        </td>
        <td>
          <%= link_to issue_path(subscriber), title: "#{t('title.action.generate')}/#{t('title.action.show')} #{t('mongoid.models.certificate')}",
                      id: "generate_#{subscriber.id}", class: 'btn btn-primary',
                      method: :delete do %>
            <i class="bi-download"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_certificate_subscriber_path(@certificate, subscriber),
                      title: "#{t('title.action.edit')} #{t('mongoid.attributes.subscriber.profile')}/#{t('mongoid.attributes.subscriber.theme')}", class: 'btn btn-primary' do %>
            <i class="bi-pencil"></i>
          <% end %>
        </td>
        <td>
          <%= form_tag(certificate_send_by_email_path(@certificate), method: :post, class: 'form-inline') do %>
            <%= button_tag type: 'submit', class: 'btn btn-primary',
                           title: "#{t('title.action.send')} #{t('mongoid.models.certificate')}",
                           data: { confirm: t('title.action.are_you_sure') } do %>
              <i class="bi-send"></i>
            <% end %>
            <%= hidden_field_tag 'subscriber_id', subscriber.id %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_username_path(subscriber.user, subscriber_id: subscriber.id),
                      title: "#{t('title.action.edit')} #{t('mongoid.attributes.user.full_name')}",
                      id: "edit_username_#{subscriber.id}", class: 'btn btn-primary' do %>
            <i class="bi-person-check"></i>
          <% end %>
        </td>
        <td>
          <%= link_to certificate_subscriber_path(@certificate, subscriber),
                      title: t('title.action.destroy'),
                      class: 'btn btn-danger', method: :delete,
                      data: { confirm: t('title.action.are_you_sure') } do %>
            <i class="bi-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subscribers/edit.html.erb
<%= render partial: 'form', layout: 'shared/form', locals: { cols: 6, title: "#{t('title.action.editing')} #{t('mongoid.models.subscriber')} <br/> #{@certificate.category.name.capitalize}: #{@certificate.title}<br/>#{t('mongoid.models.user')}: #{@subscriber.user.full_name} (#{@subscriber.user.email}) ", url: certificate_subscriber_path(@certificate), form: 'edit' } %>

app/views/subscribers/index.html.erb
<%= render partial: 'index', layout: 'shared/form',
           locals: {
             cols: 12,
             title: "#{t('mongoid.models.certificate')} \
                     #{@certificate.category.preposition} \
                     #{@certificate.category.name} #{@certificate.title} - \
                     #{@subscribers_count} #{t('title.models.subscribers')}"
           } %>

app/views/subscribers/new.html.erb
<%= render partial: 'form', layout: 'shared/form', locals: { cols: 6, title: "#{t('title.action.new')} #{t('mongoid.models.subscriber')}<br/>#{@certificate.category.name.capitalize}: #{@certificate.title}", url: certificate_subscribers_path(@certificate), form: 'new' } %>