config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'

  resources :certificates do
    resources :subscribers
    resources :import_subscribers, only: %i[new create]
    resource :send_by_email, only: %i[create]
  end

  resources :templates
  resources :issues, only: %i[index update destroy]
  resources :validates, only: %i[new create show]
  resources :usernames, only: %i[edit update]

  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    authenticate :user, lambda { |user| user.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/certificate.rb
class Certificate
  VALID_SITE_REGEX = %r{(^$)|(^(http|https)://[a-z0-9]+([\-.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?/.*)?$)}

  include Mongoid::Document
  include Mongoid::Timestamps::Short
  include Mongoid::Slug

  field :title, type: String
  field :initial_date, type: Date
  field :final_date, type: Date
  field :workload, type: String
  field :local, type: String
  field :site, type: String

  slug :title

  mount_uploader :image, CertificateImageUploader

  validates_presence_of :template_id, :category_id, :title, :initial_date,
                        :final_date, :workload, :local
  validates_length_of :title, maximum: 200
  validates_format_of :site, with: VALID_SITE_REGEX

  belongs_to :user
  belongs_to :template
  belongs_to :category
  has_many :subscribers, dependent: :restrict_with_error

  scope :with_relations, -> { includes(:user, :template, :category) }

  def destroy_image
    image_file = image.file

    ImageFile.remove(image_file) if image_file

    image_cached = Rails.root.join('tmp', 'certificates', id.to_s)

    File.delete(image_cached) if File.exist?(image_cached)
  end

  def template_image
    CertificateTemplateImage.new(self).pull
  end

  def queue_emails(subscriber_id, params)
    if subscriber_id
      subscriber_ = Subscriber.find(subscriber_id)

      subscriber_&.send_certificate_by_email
    else
      subscribers_ = Subscriber.search(params, self)[:records]

      subscribers_.each(&:send_certificate_by_email)
    end
  end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_certificate, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[new create edit update]
  before_action :authorization, only: %i[show edit]

  def index
    query = current_user.certificates.with_relations.order(initial_date: :desc)
    @pagy, @records = pagy(query, count: query.count)
  end

  def show; end

  def new
    @certificate = Certificate.new
  end

  def edit
    @certificate.initial_date = I18n.l(@certificate.initial_date)
    @certificate.final_date = I18n.l(@certificate.final_date)
  end

  def create
    @certificate = Certificate.new(certificate_params)
    @certificate.user = current_user

    if @certificate.save
      redirect_to @certificate, notice: t('notice.created', model: t('mongoid.models.certificate'))
    else
      render :new
    end
  end

  def update
    @certificate.destroy_image if certificate_params[:image] || certificate_params[:remove_image] == '1'

    if @certificate.update(certificate_params)
      redirect_to @certificate, notice: t('notice.updated', model: t('mongoid.models.certificate'))
    else
      render :edit
    end
  end

  def destroy
    @certificate.destroy_image
    @certificate.destroy

    if @certificate.errors.blank?
      redirect_to certificates_path,
                  notice: t('notice.destroyed', model: t('mongoid.models.certificate'))
    else
      redirect_to certificate_path(@certificate),
                  notice: t('notice.delete.restriction.certificates')
    end
  end

  private

  def set_certificate
    @certificate = current_user.certificates.find(params[:id])
  end

  def set_categories
    @categories = Category.all.by_name
  end

  def certificate_params
    params.require(:certificate).permit(
      :title, :initial_date, :final_date, :workload, :local,
      :site, :image, :image_cache, :remove_image, :template_id, :category_id
    )
  end

  def authorization
    return if @certificate

    redirect_to certificates_path,
                notice: t('notice.not_found', model: t('mongoid.models.certificate')) and return
  end
end

app/views/certificates/_form.html.erb
<%= simple_form_for(@certificate) do |f| %>
  <%= f.input :template_id, collection: current_user.templates.order(name: :asc), autofocus: true, input_html: { class: 'form-select' } %>
  <%= f.input :category_id, collection: @categories, input_html: { class: 'form-select' } %>
  <%= f.input :title %>
  <%= f.input :initial_date, input_html: { class: 'date' } %>
  <%= f.input :final_date, input_html: { class: 'date' } %>
  <%= f.input :workload %>
  <%= f.input :local %>

  <div class="card">
    <div class="card-header bg-success text-white"><%= t('hint.title.certificate') %></div>
    <div class="card-body">
      <%= f.input :site, as: :url, placeholder: t('hint.site') %>

      <%= show_image(@certificate, @certificate.title) %>
      <%= f.input :image_cache, as: :hidden %>
      <%= f.input :image, as: :file, hint: t('hint.image', size: '300x150'), input_html: { class: 'form-control' } %>

      <% if @certificate.title? %>
        <%= f.check_box :remove_image %>
        <%= label_tag "certificate_remove_image", "#{t('title.action.destroy')} #{t('mongoid.attributes.certificate.image')}" %>
      <% end %>
    </div>
  </div>

  <hr/>
  <%= f.button :submit, class: 'btn btn-primary btn-submit' %>
  <%= link_to t('title.action.back'), certificates_path, class: 'btn btn-secondary' %>
<% end %>

app/views/certificates/_index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to "#{t('title.action.new')} #{t('mongoid.models.certificate')}", new_certificate_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-10 d-flex justify-content-end">
    <%= render 'shared/paginate', pagy: @pagy %>
  </div>
</div>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th width="10%"><%= t('mongoid.models.category') %></th>
      <th width="30%"><%= t('mongoid.attributes.certificate.title') %></th>
      <th width="10%"><%= t('mongoid.attributes.certificate.initial_date') %></th>
      <th width="10%"><%= t('mongoid.attributes.certificate.final_date') %></th>
      <th width="5%" class="text-center"><%= t('mongoid.attributes.certificate.workload') %></th>
      <th width="5%" class="text-center"><%= t('mongoid.attributes.certificate.image') %></th>
      <th width="30%" class="text-center"><%= t('title.action.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |certificate| %>
      <tr>
        <td><%= certificate.category.name %></td>
        <td><%= certificate.title %></td>
        <td><%= l certificate.initial_date %></td>
        <td><%= l certificate.final_date %></td>
        <td class="text-center"><%= certificate.workload %></td>
        <td class="text-center"><%= show_image(certificate, certificate.title) %></td>
        <td class="text-center">
          <%= link_to t('title.action.show'), certificate, class: 'btn btn-primary' %>
          <%= link_to t('title.action.edit'), edit_certificate_path(certificate), class: 'btn btn-primary' %>
          <%= link_to t('title.models.subscribers'), certificate_subscribers_path(certificate), class: 'btn btn-primary' %>
          <%= link_to t('title.action.destroy'), certificate, class: 'btn btn-danger', method: :delete, data: { confirm: t('title.action.are_you_sure') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/certificates/_show.html.erb
<table class="table table-responsive">
  <tbody>
    <tr>
      <th><%= t('mongoid.models.template') %></th>
      <td><%= @certificate.template.name %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.models.category') %></th>
      <td><%= @certificate.category.name %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.title') %></th>
      <td><%= @certificate.title %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.initial_date') %></th>
      <td><%= l @certificate.initial_date %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.final_date') %></th>
      <td><%= l @certificate.final_date %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.workload') %></th>
      <td><%= @certificate.workload %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.local') %></th>
      <td><%= @certificate.local %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.site') %></th>
      <td><%= @certificate.site %></td>
    </tr>
    <tr>
      <th><%= t('mongoid.attributes.certificate.image') %></th>
      <td><%= show_image(@certificate, @certificate.title, '200x100') %></td>
    </tr>
  </tbody>
</table>

<%= link_to t('title.action.edit'), edit_certificate_path(@certificate), class: 'btn btn-primary' %>
<%= link_to t('title.action.back'), certificates_path, class: 'btn btn-secondary' %>

app/views/certificates/edit.html.erb
<%= render partial: 'form', layout: 'shared/form', locals: { cols: 6, title: "#{t('title.action.editing')} #{t('mongoid.models.certificate')}", certificate: @certificate } %>

app/views/certificates/index.html.erb
<%= render partial: 'index', layout: 'shared/form', locals: { cols: 12,
  title: "#{@records.size} #{t('title.models.certificates')}"} %>

app/views/certificates/new.html.erb
<%= render partial: 'form', layout: 'shared/form', locals: { cols: 6, title: "#{t('title.action.new')} #{t('mongoid.models.certificate')}", certificate: @certificate } %>

app/views/certificates/show.html.erb
<%= render partial: 'show', layout: 'shared/form', locals: { cols: 6, title: t('mongoid.models.certificate') } %>